%step

%     ******************************************************************
function[eta_left,eta_right,eta_left_new,eta_right_new]= step(n_bins_total,...
    g_left,g_right,eta_left,eta_right,eta_left_new,eta_right_new)
%     ******************************************************************                                              
      n=1;
     eta_left_new(n)=...
     eta_left(n)*g_left(1,n)+...
     eta_left(n+1)*g_left(2,n)+...
     eta_left(n+2)*g_left(3,n)+...
     eta_right(n)*g_left(5,n)+...
     eta_right(n+1)*g_left(6,n);
        
     eta_right_new(n)=...
     eta_right(n)*g_right(1,n)+...
     eta_left(n+1)*g_right(4,n)+...
     eta_left(n)*g_right(5,n);

      n=2;
     eta_left_new(n)=...
     eta_left(n)*g_left(1,n)+...
     eta_left(n+1)*g_left(2,n)+...
     eta_left(n+2)*g_left(3,n)+...
     eta_right(n-1)*g_left(4,n)+...
     eta_right(n)*g_left(5,n)+...
     eta_right(n+1)*g_left(6,n);
     
     eta_right_new(n)=...
     eta_right(n)*g_right(1,n)+...
     eta_right(n-1)*g_right(2,n)+...
     eta_left(n+1)*g_right(4,n)+...
     eta_left(n)*g_right(5,n)+...
     eta_left(n-1)*g_right(6,n);
      
      n=n_bins_total-1;
        
     eta_left_new(n)=...
     eta_left(n)*g_left(1,n)+...
     eta_left(n+1)*g_left(2,n)+...
     eta_right(n-1)*g_left(4,n)+...
     eta_right(n)*g_left(5,n)+...
     eta_right(n+1)*g_left(6,n);
     
     eta_right_new(n)=...
     eta_right(n)*g_right(1,n)+...
     eta_right(n-1)*g_right(2,n)+...
     eta_right(n-2)*g_right(3,n)+...
     eta_left(n+1)*g_right(4,n)+...
     eta_left(n)*g_right(5,n)+...
     eta_left(n-1)*g_right(6,n);

      n=n_bins_total;
      
     eta_left_new(n)=...
     eta_left(n)*g_left(1,n)+...
     eta_right(n-1)*g_left(4,n)+...
     eta_right(n)*g_left(5,n);
     
     eta_right_new(n)=...
     eta_right(n)*g_right(1,n)+...
     eta_right(n-1)*g_right(2,n)+...
     eta_right(n-2)*g_right(3,n)+...
     eta_left(n)*g_right(5,n)+...
     eta_left(n-1)*g_right(6,n);

      for n=3:n_bins_total-2
     eta_left_new(n)=...
     eta_left(n)*g_left(1,n)+...
     eta_left(n+1)*g_left(2,n)+...
     eta_left(n+2)*g_left(3,n)+...
     eta_right(n-1)*g_left(4,n)+...
     eta_right(n)*g_left(5,n)+...
     eta_right(n+1)*g_left(6,n);
     
     eta_right_new(n)=...
     eta_right(n)*g_right(1,n)+...
     eta_right(n-1)*g_right(2,n)+...
     eta_right(n-2)*g_right(3,n)+...
     eta_left(n+1)*g_right(4,n)+...
     eta_left(n)*g_right(5,n)+...
     eta_left(n-1)*g_right(6,n);
      end 

      for n=1:n_bins_total
        eta_left(n)=eta_left_new(n);
        eta_right(n)=eta_right_new(n);

      end  
      
      
      end